### ISSUE TITLE
A way to serialize and deserialize LDUser

### ISSUE THREAD

**Issue by davebarda** [launchdarkly/java-server-sdk#199] opened 2020-08-03 17:41 UTC
**Is your feature request related to a problem? Please describe.**
I would like to have the ability use Gson or other json serialization library in order to serialize/deserialize LDUser
and transfer it between microservices.

**Describe the solution you'd like**
I think that as you already have Gson serialization, just need deserialization that takes the created LDUser and
set LDValue null in case that the specific field is null

**Additional context**
I tried just to use LDUser ldUser = GSON.fromJson(ldUserStr, LDUser.class);
but then I receive NPE with the following stacktrace:
java.lang.NullPointerException: null
	at com.launchdarkly.client.LDUser$UserAdapterWithPrivateAttributeBehavior.write(LDUser.java:201)
	at com.launchdarkly.client.LDUser$UserAdapterWithPrivateAttributeBehavior.write(LDUser.java:180)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.launchdarkly.client.EventOutputFormatter.writeUser(EventOutputFormatter.java:186)
	at com.launchdarkly.client.EventOutputFormatter.writeOutputEvent(EventOutputFormatter.java:81)
	at com.launchdarkly.client.EventOutputFormatter.writeOutputEvents(EventOutputFormatter.java:31)
	at com.launchdarkly.client.DefaultEventProcessor$SendEventsTask.run(DefaultEventProcessor.java:644)

I am using version 4.12.1 of the library.
Thanks, David.

**Comment by eli-darkly** [comment] 2020-08-03 18:05
Hi. As you guessed, the issue is that there isn't (in that version of the SDK) a custom deserializer for LDUser. None was needed for the SDK's own use; the custom serializer was implemented because the SDK serializes user data as part of analytics events.

In version 5.0.0 and above, there's a well-defined set of SDK classes that fully support JSON serialization and deserialization, including LDUser. I realize that you may not be at a convenient point to migrate to 5.x right now, but it's unlikely that we would be adding new features to 4.x at this point.

Does your code need to actually do things with the properties of the deserialized user, or are you just transferring it as-is to another service? If it's the latter then you could simply represent it as `JsonElement` so it would be treated as generic JSON data.

**Comment by davebarda** [comment] 2020-08-03 18:26
As we use some data to evaluate flags, I'm revealing more data than I want to reveal in regular getAccount request on my account service, so I want to represent it as LDUser(or similar) in order to transfer it as a flag specific information(which is encapsulated)

**Comment by eli-darkly** [comment] 2020-08-03 18:36
I'll take a look at what the current behavior is for deserializing with the default Gson behavior, and see if it's possible to make the SDK tolerate the result of that better (i.e. if it is really _only_ a matter of whether it sees a `null` somewhere that it expects `LDValue.null()`, as you suggested, then maybe that piece of code could be made null-tolerant) in which case it would be a patch rather than a new feature. But I can't say off the top of my head whether that's the case.

**Comment by davebarda** [comment] 2020-08-03 18:41
Well, I had a test that checks all the fields, the only differences I found were null fields, LDValue.null() was replaced with null on the serialization -> deserialization, Thank you!

**Comment by eli-darkly** [comment] 2020-08-05 00:52
Released version 4.14.1 with a fix for this.

If you later migrate your code to the 5.x SDK, you'll want to look at [this package](https://javadoc.io/static/com.launchdarkly/launchdarkly-java-server-sdk/5.0.0/com/launchdarkly/sdk/json/package-summary.html).

**Closed by eli-darkly** 2020-08-05 00:52 UTC
