### ISSUE TITLE
Encountered EventSource error: Operation not permitted (select/poll failed)

### ISSUE THREAD

**Issue by brettcooper** [launchdarkly/java-server-sdk#108] opened 2017-12-14 14:49 UTC
We just began using LaunchDarkly recently for feature hiding, but we are continually getting the following error:

Encountered EventSource error: Operation not permitted (select/poll failed)
com.launchdarkly.client.StreamProcessor$1.onError(StreamProcessor.java:127)

We are running a series of microservices on AWS Lambda and this is our most common error in our logs (appears over 387k times).  Please let me know if you need more details.

**Comment by levlaz** [comment] 2017-12-14 18:34
Hey Brett, 

Could you let me know which version of Java you are using? 

Do you also have any sort of sample code that we can use to try to reproduce this?

**Comment by levlaz** [comment] 2017-12-14 18:41
Brett, could you also run this with DEBUG logs enabled? https://github.com/launchdarkly/java-client#logging

If you have any sensitive info in the logs feel free to email them to me instead of posting here. lev@launchdarkly.com 

GPG: http://pgp.mit.edu/pks/lookup?op=vindex&search=0x239FBEC8D2512A3F

**Comment by brettcooper** [comment] 2017-12-15 15:08
Hi @levlaz ,

Thanks for the quick response!  We are running Java 1.8.0_74.  I will try to enable debug logging and see if I can get a stack trace for you.  Here is some sample code we are running:

```
public class LaunchDarklyClientProvider implements Provider<LDClient> {

    public static final String API_KEY_CONFIG = "LAUNCHDARKLY_SDK_KEY";

    private final LDClient ldClient;

    @SuppressFBWarnings("WEM_WEAK_EXCEPTION_MESSAGING")
    public LaunchDarklyClientProvider() {
        String key = getConfigValue(API_KEY_CONFIG);
        if (StringUtils.isNullOrEmpty(key)) {
            throw new IllegalStateException(API_KEY_CONFIG + " must be non-null");
        }
        ldClient = new LDClient(key);
    }

    @Override
    public LDClient get() {
        return ldClient;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}
```
```
public class FeatureFlipLaunchDarklyProvider implements Provider<FeatureFlip> {

    private final FeatureFlip featureFlip;

    @Inject
    public FeatureFlipLaunchDarklyProvider(LDClient ldClient) {
        featureFlip = new FeatureFlipLaunchDarkly(ldClient);
    }

    public FeatureFlip get() {
        return featureFlip;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}
```
```
public class FeatureFlipLaunchDarkly implements FeatureFlip {

    public static final LDUser ANONYMOUS = new LDUser.Builder("anonymous").anonymous(true).build();

    private static final Logger LOG = LoggerFactory.getLogger(FeatureFlipLaunchDarkly.class);

    private final LDClient client;

    @SuppressFBWarnings("WEM_WEAK_EXCEPTION_MESSAGING")
    public FeatureFlipLaunchDarkly(LDClient client) {
        if (client == null) {
            throw new IllegalArgumentException("LDClient must not be null");
        }
        this.client = client;
    }

    @Override
    public boolean isFeatureEnabled(String key) {
        boolean isEnabled = client.boolVariation(key, ANONYMOUS, false);
        LOG.trace("feature \"{}\" == {}", key, isEnabled);
        return isEnabled;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}
```
```
public abstract class FeatureFlipProxyProvider<T> implements Provider<T> {

    private final T proxy;

    @SuppressFBWarnings("WEM_WEAK_EXCEPTION_MESSAGING")
    protected FeatureFlipProxyProvider(Class<T> type,
                                       FeatureFlip featureFlip,
                                       T enabledImplementation,
                                       T disabledImplementation) {
        Feature feature = type.getAnnotation(Feature.class);
        if (feature == null) {
            throw new IllegalArgumentException(type.getName() + " must be annotated with @Feature");
        }
        String key = feature.key();
        ClassLoader classLoader = FeatureFlipProxyProvider.class.getClassLoader();
        Class<?>[] interfaces = {type};
        proxy = (T) Proxy.newProxyInstance(classLoader, interfaces,
                                           (proxy1, method, args) -> featureFlip.isFeatureEnabled(key) ?
                                                   method.invoke(enabledImplementation, args) :
                                                   method.invoke(disabledImplementation, args));
    }

    @Override
    public T get() {
        return proxy;
    }
}
```
```
public interface FeatureFlip {

    boolean isFeatureEnabled(String key);

    /**
     * Simple config key lookup in application.conf followed by system environment
     * Intentionally not depending on other config components to not cause circular dependency
     */
    static String getConfigValue(String key) {
        if (StringUtils.isBlank(key)) {
            return null;
        }

        Config application = ConfigFactory.load();
        if (application.hasPath(key) && StringUtils.isNotEmpty(application.getString(key))) {
            return application.getString(key);
        }

        String envConfig = System.getenv(key);
        if (StringUtils.isNotEmpty(envConfig)) {
            return envConfig;
        }

        return "";
    }
}
```

**Comment by atrakh** [comment] 2018-02-15 02:15
Hi @brettcooper,

I've been investigating this issue, and haven't yet been able to reproduce the error you're seeing. The error you're seeing seems to be pretty elusive, and having researched this issue in the past, I believe such errors are fairly isolated to AWS products.

To help with investigation, can you confirm which version of the LaunchDarkly Java SDK you're using? From your partial stack trace, I noticed that you may be using an older version of the client.    We have updated the dependency which is producing these errors since then (EventSource), so it upgrading may be worth a try.

Also, does it look like the lambda executions that generate this error have been producing your desired results (no uncaught exceptions, `boolVariation` returns the correct value)? If that's not the case, we'd be able to update the client to at least handle these errors gracefully.

**Comment by brettcooper** [comment] 2018-02-19 18:33
Hi @atrakh,

We are using launchdarkly-client 2.5.1.  It does look like there is a newer version of the client (2.6.0) that we can upgrade to.  I will upgrade us to the latest client and see if this error goes away or not.  Yes, it does appear that the lamdba is producing our desired results despite this error.

Thanks,
Brett

**Comment by pmalon** [comment] 2018-05-03 10:08
@brettcooper have you managed to get around this issue? I am getting very similar error with RabbitMQ client on AWS lambda...

**Comment by brettcooper** [comment] 2018-05-03 13:37
@pmalon No, we are still having this issue.

**Comment by bwoskow-ld** [comment] 2019-04-18 18:08
Hi @brettcooper,

Can you distinguish if the error happens while the Lambda is executing or upon terminating? I'm curious if LDClient has failed operations during normal execution or if it is something specific to operating the connections while simultaneously being shut down.

**Comment by khozzy** [comment] 2019-06-16 06:48
I'm getting the same error but when connecting to MongoDb on AWS Lambda function...

**Comment by eli-darkly** [comment] 2020-06-01 19:07
Closing this as the reporter hasn't responded in a year and, per the last comment, the issue doesn't seem to be specific to this SDK.

**Closed by eli-darkly** 2020-06-01 19:07 UTC
